### ISSUE TITLE
Qwiic Lidar-Lite V4 Measurement issue

### ISSUE THREAD

**Issue by jrwitte** [sparkfunX/Qwiic_Lidar_Lite#1]
Experimenting with LIDAR example created by Priyanka Makin@SparkX Labs. Works fine at close range but seems to overflow if I get more than 256cm away as it returns to zero and resumes the count up. Seems like the library LIDARLite_v4LED.h library can only go to 8 bits wide. The device is supposed to go up to 10m range. Am I missing something or maybe using the wrong example?

**Comment by makin-stuff** [comment]
@jrwitte I'm closing this issue here and re-opening on the [library repo](https://github.com/sparkfun/SparkFun_LIDARLitev4_Arduino_Library). I'll be working on this now.
